<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme-libretto" # the subpath of your site, e.g. /blog
url: "https://ferrolho.github.io" # the base hostname & protocol for your site
github_username:    jekyll
instagram_username: jekyllrb
twitter_username:   jekyllrb

# Build settings
markdown: kramdown
=======

# SEO settings
title: Neuron Sketch
description: "A blog about computational neuroscience"
keywords: "computational neuroscience, NEST, network dynamics, recurrent network"
url: http://hanlu.io
baseurl: "/blog"
# baseurl: null

google_analytics: 
repo: http://github.com/erbb4/blog
disqus_shortname: "neuron-sketch.disqus.com"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

# source: /
# destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Han Lu
  job      : Frontend Engineer
  bio      : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb    : /images/author.jpg
  email    : nandomoreira.me@gmail.com
  url      : http://nandomoreira.me
  github   : http://github.com/nandomoreirame
  twitter  : http://twitter.com/nandomoreirame
  facebook : http://facebook.com/fernando.dev
  linkedin : http://linkedin.com/in/nandomoreirame

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
>>>>>>> bd0d7199b6507c7899ac117eb2312afecd2753b3
