
# SEO settings
title: Neuron Sketch
description: "A blog about computational neuroscience"
keywords: "neural plasticity, computational neuroscience, optogenetics, non-invasive brain stimulation"
url: http://hanlu.io
baseurl: "/blog"
# baseurl: null

# navbar pages
navbar:
  - slug: /photos
    title: Photos
  - slug : /about
    title: About
  - slug : /archive
    title: Archive


# collections

collections:
  research-notes: # the name should be the same as the folder name except the underscore. e.g., the folder name should be "_notes"
    title: Notes
    output: true
    source_link: https://github.com/erbb4/notes
  photos: # this is for the photo gallery
    title: Photos
    output: true




# Author settings
author:
  name     : Han Lu # Also the name shown on the front page
  job      : Postdoctoral researcher # Also the profession shown on the front page
  bio      : "Neuroscience" # Also shown on the front page
  thumb    : /assets/images/author.jpg # change it as you wish
  email    : hi@hanlu.io
  url      : http://hanlu.io
  github   : http://github.com/ErbB4
  #twitter  : http://twitter.com/nandomoreirame # change this
  #facebook : http://facebook.com/fernando.dev
  #linkedin : http://linkedin.com/in/nandomoreirame
  resumelink: http://hanlu.io

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

google_analytics:
repo: https://github.com/ErbB4/blog
disqus_shortname: "neuron-sketch"

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

# paginate: 4
# paginate_path: "/page/:num/"
comments: true

# source: source
# destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded



gems:
  # - bourbon
  # - jekyll-paginate


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
